// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5lbXUV-YhjuBAgJoR0scN0_DMvyjC7tc',
    appId: '1:919664065190:web:5c7acb627d2288ac8d1267',
    messagingSenderId: '919664065190',
    projectId: 'projet-final-73218',
    authDomain: 'projet-final-73218.firebaseapp.com',
    storageBucket: 'projet-final-73218.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWc7-54en0P7U4DPdb7aaj49bcgudaI34',
    appId: '1:919664065190:android:e0a76228e15c80868d1267',
    messagingSenderId: '919664065190',
    projectId: 'projet-final-73218',
    storageBucket: 'projet-final-73218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByDeXYb1catJxKf_s0L-r436ZkToGZYGU',
    appId: '1:919664065190:ios:6f6e8b62550f53f18d1267',
    messagingSenderId: '919664065190',
    projectId: 'projet-final-73218',
    storageBucket: 'projet-final-73218.appspot.com',
    iosClientId: '919664065190-j488ebcjhtvo8oj7b2ihehgmeh463da9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFinalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByDeXYb1catJxKf_s0L-r436ZkToGZYGU',
    appId: '1:919664065190:ios:6f6e8b62550f53f18d1267',
    messagingSenderId: '919664065190',
    projectId: 'projet-final-73218',
    storageBucket: 'projet-final-73218.appspot.com',
    iosClientId: '919664065190-j488ebcjhtvo8oj7b2ihehgmeh463da9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFinalFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5lbXUV-YhjuBAgJoR0scN0_DMvyjC7tc',
    appId: '1:919664065190:web:e717a91bf6dac2cf8d1267',
    messagingSenderId: '919664065190',
    projectId: 'projet-final-73218',
    authDomain: 'projet-final-73218.firebaseapp.com',
    storageBucket: 'projet-final-73218.appspot.com',
  );
}
